# Generated by Django 5.1.3 on 2025-06-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='contact_preferences',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='display_preferences',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='location_preferences',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notification_preferences',
        ),
    ]
