# Generated by Django 5.1.3 on 2025-05-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AddField(
            model_name='userrole',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
