# Generated by Django 5.1.3 on 2025-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivereded', 'delivereded'), ('cancelleded', 'cancelleded')], default='pending', max_length=20),
        ),
    ]
