# Generated by Django 5.1.3 on 2025-06-02 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_type_cc6610_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='notification_title',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='notification_type',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'user'], name='notificatio_notific_97285d_idx'),
        ),
    ]
