# Generated by Django 5.1.3 on 2025-06-06 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dairyinventory',
            options={'ordering': ['expiry_date']},
        ),
        migrations.AlterModelOptions(
            name='dairyproduction',
            options={'ordering': ['-production_date']},
        ),
        migrations.RenameField(
            model_name='dairyinventory',
            old_name='temperature',
            new_name='storage_temperature',
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='batch_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dairyproduction',
            name='fat_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dairyproduction',
            name='protein_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
